name: cauth-dapp
services:
  nginx:
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped
    build: .
    #ports:
    #  - "8080:80"
    networks:
      proxy-net:
        ipv4_address: 172.0.0.252
networks:
  proxy-net:
    external: true
