services:
  wikidb:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - wikidb-data:/var/lib/postgresql/data 

  wiki:
    image: requarks/wiki:2
    depends_on:
      - wikidb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    networks:
      default:
      proxy-net:
        ipv4_address: 172.0.0.2
volumes:
  wikidb-data:
networks:
  proxy-net:
    external: true
